ingress:
  external_service_ip: DEFINED-AS-VALUE

metallb:
  rbac:
    create: false

  prometheus:
    scrapeAnnotations: true

  serviceAccounts:
    controller:
      create: false
      name: default
    speaker:
      create: false
      name: default

  controller:
    nodeSelector:
      species: master

  # configInline:
  # defined in region secrets
