# Default values for rabbitmq.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  user_suffix: ""
  master_password: ""

image: rabbitmq
imageTag: 3.7-management
## Specify a imagePullPolicy
## 'Always' if imageTag is 'latest', else set to 'IfNotPresent'
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
# imagePullPolicy:


ports:
  public: 5672
  management: 15672
  clustering: 25672
  epmd: 4369

users:
  default:
    user: rabbitmq
    password: null
  admin:
    user: admin
    password: null

persistence:
  enabled: false
  accessMode: ReadWriteMany
  size: 10Gi
  # Re-use existing (unmanged) PVC
  # existingClaim: claimName

resources:
  enabled: false
  limits:
    memory: 128Mi
    cpu: 500m
  requests:
    memory: 128Mi
    cpu: 500m

metrics:
  enabled: true
  image: kbudde/rabbitmq-exporter
  imageTag: v0.28.0
  user: monitoring
  password: null
  port: 9150
  resources:
    enabled: false
    limits:
      memory: 128Mi
      cpu: 500m
    requests:
      memory: 128Mi
      cpu: 500m

plugins:
  - rabbitmq_management
  - rabbitmq_tracing
  - rabbitmq_peer_discovery_k8s

replicas: 1
erlangCookie: "DefaultErlangSecretCookie"
hipe_compile: "true"

upgrades:
  updateStrategy: RollingUpdate
  revisionHistory: 3
